# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: '$(CronValue)'
    displayName: Scheduled running
    branches:
      include:
        - master
    always: true


trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- script: python -m pip install --upgrade pip && pip install --target=$(workingDirectory)$(RunScript) -r ./requirements.txt
  displayName: 'Run a one-line script'

- script: python update_param.py -u $(wsuserkey) -o $(wsorgtoken) -l $(wsurl) -a $(azureurl) -ao $(azureorg) -ap $(azurepat) -m $(modificationtypes) -utc $(utcdelta) -st $(synctime) -sr $(syncrun) -is $(initialsync) -id $(initialstartdate) -apj $(azureproject) -wpj $(wsprojects)
  displayName: 'Run a multi-line script'
- script: python ws_wi_sync/ws_wi_integration.py
