# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: "0 */1 * * *"
    displayName: Scheduled running syncronization script
    branches:
      include:
        - master
    always: true


trigger: none
pr: none

pool:
  vmImage: ubuntu-latest
   
variables:
   - name: WS_AZUREORG
     value: ''
   - name: WS_AZUREAREA
     value: ''
   - name: WS_AZUREPROJECT
     value: ''
   - name: WS_AZURETYPE
     value: 'Task'
   - name: WS_AZUREURL
     value: 'https://dev.azure.com/'
   - name: WS_CUSTOMFIELDS
     value: ''
   - name: WS_MODIFICATIONTYPES
     value: 'All'
   - name: WS_RESET
     value: 'False'
   - name: WS_UTCDELTA
     value: '0'
   - name: WS_PRODUCTTOKEN
     value: ''
   - name: WS_PROJECTTOKEN
     value: ''
   - name: WS_URL
     value: ''

steps:
- bash:
- $ {{if eq(variables.WS_AZUREAREA,'')}}: echo "##vso[task.setvariable variable=areapath;]${{variables.WS_AZUREPROJECT}}"
  ${{else}}: echo "##vso[task.setvariable variable=areapath;]${{variables.WS_AZUREAREA}}"
  displayName: 'Environment variables preparation'

#- bash: echo "##vso[task.setvariable variable=areapath;]${{variables.area}}"
#  condition: ne(variables.area,'')
#  displayName: 'Environment variables preparation #2'


- script: python -m pip install --upgrade pip && pip install --target=$(workingDirectory)$(RunScript) -r ./requirements.txt
  displayName: 'Install dependencies'

- script: echo 'Need to set Product or Project Token'
  condition: and(eq(variables.WS_PRODUCTTOKEN,''), eq(variables.WS_PROJECTTOKEN,''))
  displayName: 'Preparation config file'

#- script: python update_param.py --user-key $(userkey) --api-key $(apikey) --url $(WS_URL) --azureurl $(WS_AZUREURL) --azureorg $(WS_AZUREORG) --azurepat $(azurepat) --type $(WS_MODIFICATIONTYPES) --utcdelta $(WS_UTCDELTA) --azureproject $(WS_AZUREPROJECT) --wsprojecttoken $(WS_PROJECTTOKEN) --azurearea $(areapath) --azuretype $(WS_AZURETYPE) --customfields $(WS_CUSTOMFIELDS) --reset $(WS_RESET)
#  condition: and(eq(variables.WS_PRODUCTTOKEN,''), ne(variables.WS_PROJECTTOKEN,''))
#  displayName: 'Preparation config file'

#- script: python update_param.py --user-key $(userkey) --api-key $(apikey) --url $(WS_URL) --azureurl $(WS_AZUREURL) --azureorg $(WS_AZUREORG) --azurepat $(azurepat) --type $(WS_MODIFICATIONTYPES) --utcdelta $(WS_UTCDELTA) --azureproject $(WS_AZUREPROJECT) --wsproducttoken $(wsproducttoken) --azurearea $(areapath) --azuretype $(WS_AZURETYPE) --customfields $(WS_CUSTOMFIELDS) --reset $(WS_RESET)
#  condition: and(ne(variables.WS_PRODUCTTOKEN,''), eq(variables.WS_PROJECTTOKEN,''))
#  displayName: 'Preparation config file'

- script: python update_param.py --user-key $(userkey) --api-key $(apikey) --url $(WS_URL) --azureurl $(WS_AZUREURL) --azureorg $(WS_AZUREORG) --azurepat $(azurepat) --type $(WS_MODIFICATIONTYPES) --utcdelta $(WS_UTCDELTA) --azureproject $(WS_AZUREPROJECT) --wsproducttoken $(WS_PRODUCTTOKEN) --wsprojecttoken $(WS_PROJECTTOKEN) --azurearea $(areapath) --azuretype $(WS_AZURETYPE) --customfields $(WS_CUSTOMFIELDS) --reset $(WS_RESET)
  #condition: and(ne(variables.WS_PRODUCTTOKEN,''), ne(variables.WS_PROJECTTOKEN,''))
  displayName: 'Preparation config file'

- script: python ws_azure_workitems_integration/wi_integration.py
  displayName: 'Running sync tool'

- bash: echo "##vso[task.setvariable variable=reset;]False"
