# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: "0 */1 * * *"
    displayName: Scheduled running syncronization script
    branches:
      include:
        - master
    always: true


trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
   - name : prd
     value : $(wsproducts)
   - name : prj
     value : $(wsprojects)
   - name: area
     value: $(azurearea)
   - name: areapath
     ${{if eq(variables.area,'')}} :
        value: $(azureproject)    
     ${{if ne(variables.area,'')}}:   
        value: $(azurearea)    

steps:
- script: echo $(azureproject)

- script: python -m pip install --upgrade pip && pip install --target=$(workingDirectory)$(RunScript) -r ./requirements.txt
  displayName: 'Install dependecies'

- script: echo 'Need to define Product or Project'
  condition: and(eq(variables.prd,''), eq(variables.prj,''))
  displayName: 'Preparation params.config'

- script: python update_param.py -u $(wsuserkey) -o $(wsorgtoken) -l $(wsurl) -a $(azureurl) -ao $(azureorg) -ap $(azurepat) -m $(modificationtypes) -utc $(utcdelta) -apj $(azureproject) -wpj $(wsprojects) -aa ${{variables.areapath}}
  condition: and(eq(variables.prd,''), ne(variables.prj,''))
  displayName: 'Preparation params.config'

- script: python update_param.py -u $(wsuserkey) -o $(wsorgtoken) -l $(wsurl) -a $(azureurl) -ao $(azureorg) -ap $(azurepat) -m $(modificationtypes) -utc $(utcdelta) -apj $(azureproject) -wp $(wsproducts) -aa ${{variables.areapath}}
  condition: and(ne(variables.prd,''), eq(variables.prj,''))
  displayName: 'Preparation params.config'

- script: python update_param.py -u $(wsuserkey) -o $(wsorgtoken) -l $(wsurl) -a $(azureurl) -ao $(azureorg) -ap $(azurepat) -m $(modificationtypes) -utc $(utcdelta) -apj $(azureproject) -wp $(wsproducts) -wpj $(wsprojects) -aa ${{variables.areapath}}
  condition: and(ne(variables.prd,''), ne(variables.prj,''))
  displayName: 'Preparation params.config'

- script: python ws_azure_workitems_integration/wi_integration.py
  displayName: 'Running sync tool'
