# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: "0 */1 * * *"
    displayName: Scheduled running syncronization script
    branches:
      include:
        - master
    always: true


trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
   - name : prd
     value : $(wsproducts)
   - name : prj
     value : $(wsprojects)
   - name: area
     value: $(azurearea)
   - name: azureprj
     value: $(azureproject)  

steps:
- bash: echo "##vso[task.setvariable variable=areapath;]${{variables.azureprj}}"
  condition: eq(variables.area,'')
  displayName: 'Environment variables preparation #1'

- bash: echo "##vso[task.setvariable variable=areapath;]${{variables.area}}"
  condition: ne(variables.area,'')
  displayName: 'Environment variables preparation #2'

- script: python -m pip install --upgrade pip && pip install --target=$(workingDirectory)$(RunScript) -r ./requirements.txt
  displayName: 'Install dependencies'

- script: echo 'Need to define Product or Project'
  condition: and(eq(variables.prd,''), eq(variables.prj,''))
  displayName: 'Preparation config file'

- script: python update_param.py --userKey $(userkey) --apiKey $(apikey) --wsurl $(wsurl) --azureUrl $(azureurl) --azureorg $(azureorg) --azurepat $(azurepat) --type $(modificationtypes) --utcdelta $(utcdelta) --azureproject $(azureproject) --wsprojecttoken $(wsprojects) --azurearea $(areapath) --azuretype $(azuretype)
  condition: and(eq(variables.prd,''), ne(variables.prj,''))
  displayName: 'Preparation config file'

- script: python update_param.py --userKey $(userkey) --apiKey $(apikey) --wsurl $(wsurl) --azureUrl $(azureurl) --azureorg $(azureorg) --azurepat $(azurepat) --type $(modificationtypes) --utcdelta $(utcdelta) --azureproject $(azureproject) --wsproducttoken $(wsproducts) --azurearea $(areapath) --azuretype $(azuretype)
  condition: and(ne(variables.prd,''), eq(variables.prj,''))
  displayName: 'Preparation config file'

- script: python update_param.py --userKey $(userkey) --apiKey $(apikey) --wsurl $(wsurl) --azureUrl $(azureurl) --azureorg $(azureorg) --azurepat $(azurepat) --type $(modificationtypes) --utcdelta $(utcdelta) --azureproject $(azureproject) --wsproducttoken $(wsproducts) --wsprojecttoken $(wsprojects) --azurearea $(areapath) --azuretype $(azuretype)
  condition: and(ne(variables.prd,''), ne(variables.prj,''))
  displayName: 'Preparation config file'

- script: python ws_azure_workitems_integration/wi_integration.py
  displayName: 'Running sync tool'
